// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/murilogilfelpeto/ps-tag-onboarding-go/internal/service/models"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// GetUserByFullName provides a mock function with given fields: ctx, firstName, lastName
func (_m *Repository) GetUserByFullName(ctx context.Context, firstName string, lastName string) (*models.User, error) {
	ret := _m.Called(ctx, firstName, lastName)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByFullName")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*models.User, error)); ok {
		return rf(ctx, firstName, lastName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *models.User); ok {
		r0 = rf(ctx, firstName, lastName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, firstName, lastName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_GetUserByFullName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByFullName'
type Repository_GetUserByFullName_Call struct {
	*mock.Call
}

// GetUserByFullName is a helper method to define mock.On call
//   - ctx context.Context
//   - firstName string
//   - lastName string
func (_e *Repository_Expecter) GetUserByFullName(ctx interface{}, firstName interface{}, lastName interface{}) *Repository_GetUserByFullName_Call {
	return &Repository_GetUserByFullName_Call{Call: _e.mock.On("GetUserByFullName", ctx, firstName, lastName)}
}

func (_c *Repository_GetUserByFullName_Call) Run(run func(ctx context.Context, firstName string, lastName string)) *Repository_GetUserByFullName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Repository_GetUserByFullName_Call) Return(_a0 *models.User, _a1 error) *Repository_GetUserByFullName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_GetUserByFullName_Call) RunAndReturn(run func(context.Context, string, string) (*models.User, error)) *Repository_GetUserByFullName_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserById provides a mock function with given fields: ctx, id
func (_m *Repository) GetUserById(ctx context.Context, id string) (*models.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserById")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_GetUserById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserById'
type Repository_GetUserById_Call struct {
	*mock.Call
}

// GetUserById is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *Repository_Expecter) GetUserById(ctx interface{}, id interface{}) *Repository_GetUserById_Call {
	return &Repository_GetUserById_Call{Call: _e.mock.On("GetUserById", ctx, id)}
}

func (_c *Repository_GetUserById_Call) Run(run func(ctx context.Context, id string)) *Repository_GetUserById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Repository_GetUserById_Call) Return(_a0 *models.User, _a1 error) *Repository_GetUserById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_GetUserById_Call) RunAndReturn(run func(context.Context, string) (*models.User, error)) *Repository_GetUserById_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, user
func (_m *Repository) Save(ctx context.Context, user models.User) (*models.User, error) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.User) (*models.User, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.User) *models.User); ok {
		r0 = rf(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.User) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type Repository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - user models.User
func (_e *Repository_Expecter) Save(ctx interface{}, user interface{}) *Repository_Save_Call {
	return &Repository_Save_Call{Call: _e.mock.On("Save", ctx, user)}
}

func (_c *Repository_Save_Call) Run(run func(ctx context.Context, user models.User)) *Repository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.User))
	})
	return _c
}

func (_c *Repository_Save_Call) Return(_a0 *models.User, _a1 error) *Repository_Save_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_Save_Call) RunAndReturn(run func(context.Context, models.User) (*models.User, error)) *Repository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
